---
name: concourse

releases:
- name: concourse
  version: latest
- name: garden-runc
  version: latest
- name: postgres
  version: latest

instance_groups:
- name: web
  instances: 1
  azs: [z1]
  networks: [{name: default}]
  stemcell: trusty
  vm_type: default
  jobs:
  - release: concourse
    name: atc
    properties:
      log_level: debug
      token_signing_key: ((token_signing_key))
      external_url: https://((external_ip)):443
      basic_auth_username: atc
      basic_auth_password: ((atc_basic_auth_password))
      tls_cert: ((atc_tls_cert.certificate))
      tls_key: ((atc_tls_cert.private_key))
      tls_bind_port: 443
      postgresql:
        database: &db_name atc
        role: &db_role
          name: concourse
          password: ((postgres_password))

  - release: concourse
    name: tsa
    properties:
      log_level: debug
      host_key: ((tsa_host_key))
      token_signing_key: ((token_signing_key))
      authorized_keys: [((worker_key.public_key))]

- name: db
  instances: 1
  azs: [z1]
  networks: [{name: default}]
  stemcell: trusty
  vm_type: default
  persistent_disk_type: concourse
  jobs:
  - release: postgres
    name: postgres
    properties:
      databases:
        port: 5432
        databases:
        - name: *db_name
        roles:
        - *db_role

- name: worker
  instances: 1
  azs: [z1]
  networks: [{name: default}]
  stemcell: trusty
  vm_type: worker
  jobs:
  - release: concourse
    name: groundcrew
    consumes: {baggageclaim: {from: worker-baggageclaim}}
    properties:
      drain_timeout: 10m
      tsa: {worker_key: ((worker_key))}

  - release: concourse
    name: baggageclaim
    properties: {log_level: debug}
    provides: {baggageclaim: {as: worker-baggageclaim}}

  - release: garden-runc
    name: garden
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777

variables:
- name: postgres_password
  type: password
- name: token_signing_key
  type: rsa
- name: tsa_host_key
  type: ssh
- name: worker_key
  type: ssh
- name: atc_basic_auth_password
  type: password
- name: default_ca
  type: certificate
  options:
    is_ca: true
    common_name: ca
- name: atc_tls_cert
  type: certificate
  options:
    ca: default_ca
    common_name: ((external_ip))
    alternative_names: [((external_ip))]

stemcells:
- alias: trusty
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 30000-1200000
  update_watch_time: 10000-1200000